[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.0"
hyper = { version = "1.5.2" , features = ["server", "http1"]}
serde = { version = "1.0.217", features = ["derive"] }
